package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* miércoles 23 de marzo de 2016 15H17' CST
*/

public interface HelloOperations 
{
  String sayHello (String msj);
  void shutdown ();
} // interface HelloOperations
